######################################################################
# Automatically generated by qmake (2.01a) mar. mars 14 09:22:24 2017
######################################################################

TEMPLATE = app
QT += widgets
CONFIG += c++11
SOURCES += main.cpp \
    mainwindow.cpp \
    podarchive.cpp

# Directories

FORMS += \
    mainwindow.ui

HEADERS += \
    mainwindow.h \
    podarchive.h

STATECHARTS +=
