######################################################################
# Automatically generated by qmake (2.01a) dim. mars 5 01:56:59 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += texturebuilder.cpp
